spring:
 datasource:
   url: jdbc:postgresql://localhost:5432/login_app
   username: postgres
   password: andreea
 jpa:
  show-sql: true
#  properties:
#   hibernate:
#    dialect: org.hibernate.dialect.PostgreSQL81Dialect